### ISSUE TITLE
How can I ignore a single file?

### ISSUE THREAD

**Issue by DavidePastore** [Cyb3r-Jak3/html5validator-action#12]
Hi! First, thanks for this amazing HTML5 validator that's directly available in GitHub Actions. I tried different ways to remove a file from the validation process but without success. This is one of the attempts: 

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Other steps here
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@v0.4.2
      with:
        root: ./_site/
        extra:
          - blacklist: bad-file.html
```

How can I ignore one single file? Thanks in advance 😄

**Comment by Cyb3r-Jak3** [comment]
Hi!
So I checked and there is no way to ignore one file, the functionality does not exist in [html5validator](https://github.com/svenkreiss/html5validator).

 If you know the directory that the unwanted file will be in then you can ignore that directory. 
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@v0.4.2
      with:
        root: ./_site/
        extra: --blacklist <path/to/directory>

```

**Comment by DavidePastore** [comment]
Thanks for your answer @Cyb3r-Jak3 . The problem is that the file that I want to exclude is in the same directory of the other files, so excluding the directory in which it is contained would exclude all the other ones.

**Comment by Cyb3r-Jak3** [comment]
So yeah that means we are going to need a workaround as no functionality currently exists to simply exclude one file.

Try:
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@v0.4.2
      with:
        root: ./_site/
        extra: --match ^(?!(bad)).*$
```
This should match all files apart from any file that begins with bad.

**Comment by DavidePastore** [comment]
Hi @Cyb3r-Jak3, thanks for your support. I tried it but unfortunately I can't get it to work in the right way. This is my configuration:

```yaml
name: HTML Check
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@v0.4.2
      with:
        root: ./_site/
        extra: --match ^(?!(googledd725740c84fdc30\.html)).*$
```

The output that I get is the following:

```
Running Validator
ERROR:html5validator.validator:['Error: No documents specified.']
```

You can see the full output [here](https://github.com/Ceeresa/autocertificazione/runs/1468133366?check_suite_focus=true).

Also I created [this regexr](https://regexr.com/5h7v6) to be sure that the RegEx is working in the right way. Do you have any suggestions? Thanks in advance!

**Comment by Cyb3r-Jak3** [comment]
Can you try
```yaml
name: HTML Check
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@v0.4.3
      with:
        root: ./_site/
        extra: --match ^(?!(googledd725740c84fdc30\.html)).*$
        log_level: DEBUG
        action_debug: true

```
just to generate more verbose output for debugging.

Also, I have built the skip functionality into the linter and have an open PR here https://github.com/svenkreiss/html5validator/pull/75

**Comment by DavidePastore** [comment]
Hi @Cyb3r-Jak3, thank you for the support. I tried using the same configuration you suggested and this is the output I'm getting:

```
Running Validator
+ uses ./_site/
+ '[' -n ./_site/ ']'
+ echo 'Running Validator'
+ BuildARGS=
+ uses ''
+ '[' -n '' ']'
+ usesBoolean false
+ '[' -n false ']'
+ '[' false = true ']'
+ uses ''
+ '[' -n '' ']'
+ html5validator --root ./_site/ --log DEBUG --match '^(?!(googledd725740c84fdc30\.html)).*$'
+ tee log.log
INFO:html5validator.cli:Files to validate: 
  
INFO:html5validator.cli:Number of files: 0
DEBUG:html5validator.validator:['java', '-jar', '/usr/local/lib/python3.8/site-packages/html5validator-0.3.3-py3.8.egg/vnujar/vnu.jar', '--errors-only']
DEBUG:html5validator.validator:['Error: No documents specified.']
ERROR:html5validator.validator:Error: No documents specified.
+ result=1
+ usesBoolean true
+ '[' -n true ']'
+ '[' true = true ']'
+ echo 1
+ echo ::set-output name=result::1
1
+ exit 1
```

Do you have any suggestions? Thanks in advance!

**Comment by Cyb3r-Jak3** [comment]
@DavidePastore after experimenting and looking at the linter. It looks like this action does not currently have any way to skip a file even with using `match`.  The reason is that `match` does not use regex for pattern matching but [fnmatch](https://docs.python.org/3/library/fnmatch.html).

The good news is that I can confirm that the `skip` option, which I have an open PR for, will do exactly what we need. In the meantime, you can test locally using `docker run --rm -i -v $(pwd):/mnt -w /mnt cyb3rjak3/html5validator:experimental-alpine html5validator --root _site/ --skip googledd725740c84fdc30.html`. I am also working on a separate action that will use the experimental branch which should hopefully be completed by the end of the week.

**Comment by Cyb3r-Jak3** [comment]
@DavidePastore Making a separate action was easier than expected. Using the config below will get all the files but the ones you want. [Results](https://github.com/Cyb3r-Jak3/autocertificazione/actions/runs/390323066) (still fails but that is because of linter actions rather).

```yaml
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action-experimental@v1
      with:
        root: _site/
        skip: googledd725740c84fdc30.html
```

**Comment by DavidePastore** [comment]
@Cyb3r-Jak3 , thanks for your suggestions. Using the last experimental action it now works correctly. I'll take a note about the speed improvement I could add to the project. Thanks for your support, it's highly appreciated!

**Comment by Cyb3r-Jak3** [comment]
@DavidePastore This option now exists in this action with the latest release of v0.5

```yaml
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@v0.5
      with:
        root: _site/
        ignore: googledd725740c84fdc30.htm
```

**Comment by DavidePastore** [comment]
Hi @Cyb3r-Jak3 . Thanks for letting me know that a new version is out. Anyway a new issue appeared in the GitHub Action after the upgrade and you can check it here: https://github.com/Ceeresa/autocertificazione/pull/231. Thanks in advance! 😄

**Comment by 153957** [comment]
Unfortunately the `ignore` option now maps to `blacklist` instead of the actual `ignore` option in html5validator, would it not make more sense to use the same naming? This can be confusing.

**Comment by Cyb3r-Jak3** [comment]
@153957 Thanks for bringing this up. I made it so the same variable names are mapped starting in v0.6

**Comment by 153957** [comment]
Thank you for making the change. I have one usability question about the blacklist option, how can I provide multiple filenames/directory paths to that option?
This did not seem to work (still using the ignore option with v0.5): https://github.com/153957/153957/actions/runs/819822036/workflow

**Comment by 153957** [comment]
Ah, good to know. I changed it to the following (without the `-` before the values and directly behind `blacklist:`, otherwise it will probably still be a list, just with a single argument) 
```
      - uses: Cyb3r-Jak3/html5validator-action@v0.6
        with:
          root: .build/
          css: true
          log_level: INFO
          blacklist: index_footer.html index_header.html
```
