### ISSUE TITLE
[BUG] root does not support absolute paths

### ISSUE THREAD

**Issue by ptmkenny** [Cyb3r-Jak3/html5validator-action#25]
**Describe the bug**

When you set `root` to an absolute path, you get a "No documents specified" error.

```
Running Validator
INFO:html5validator.cli:Files to validate: 
  
INFO:html5validator.cli:Number of files: 0
Error: No documents specified.
```

**To Reproduce**

Example `workflow.yml`:

```
      - name: "TESTS: Run W3C validation."
        uses: Cyb3r-Jak3/html5validator-action@v7.0.0
        with:
          root: /tmp/artifacts/my-downloaded-site
          format: text # json, xml, gnu
          log_level: INFO # DEBUG, INFO, WARNING
          css: true # Check CSS.
```

**Additional context**

To workaround this issue, specify a relative path.
