### ISSUE TITLE
[BUG] the 'uses' attribute must be a path, a Docker image, or owner/repo@ref

### ISSUE THREAD

**Issue by Sonic0** [Cyb3r-Jak3/html5validator-action#40]
Hi @Cyb3r-Jak3, thanks for your work! I have a small problem using examples without version specifications.

**Describe the bug**

Error using this action without a specific version, like some examples in this repo:
`uses: Cyb3r-Jak3/html5validator-action`

**To Reproduce**

Create a simple workflow like mine:

```
name: test
on:
  push:
    branches-ignore:
      - main
jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: HTML5Validator
        uses: Cyb3r-Jak3/html5validator-action
        with:
          root: 'src'
```

### What is the current *bug* behavior

GitHub Workflow error:
```
[Error: .github#L1](https://github.com/madisoft/siti-scuole-pagina-cortesia/commit/b7a35049249a1c086566835a63c0fd616cdb130d#annotation_8031992949)
the 'uses' attribute must be a path, a Docker image, or owner/repo@ref
```

**Additional context**

This is an example of a failing Workflow: https://github.com/madisoft/siti-scuole-pagina-cortesia/actions/runs/3940875123
