### ISSUE TITLE
[QUESTION] What version of nu checker is used?

### ISSUE THREAD

**Issue by SilentImp** [Cyb3r-Jak3/html5validator-action#41]
## Question

Hi, I added a rule to check both HTML and CSS. 
```yaml
  html_validator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: ./
        css: true
        format: xml
```
It is checking CSS file:
```css
body > p:last-of-type {
  color: red;
}

figure > blockquote {
  margin-inline-start: 0;
}
```
and generating error: 
```xml
<message>CSS: <code xmlns="http://www.w3.org/1999/xhtml">margin-inline-start</code>: Property <code xmlns="http://www.w3.org/1999/xhtml">margin-inline-start</code> doesn't exist.</message>
```
At the same time, https://validator.w3.org/nu/#textarea show it as valid CSS (and it is valid).
I was thinking: maybe it's because the version of a validator is somehow outdated?

Regards. Anton Nemtsev.
