### ISSUE TITLE
[BUG] Bug Report for CSS margin-inline Validation Issue

### ISSUE THREAD

**Issue by Alecto** [Cyb3r-Jak3/html5validator-action#45]
**Describe the bug**
The HTML5Validator Action fails when encountering the `margin-inline` property in CSS. The validator reports that the property "doesn't exist", although it is part of modern CSS specifications.

**To Reproduce**
1. Set up the `Cyb3r-Jak3/html5validator-action` in a GitHub Actions workflow.
2. Use CSS containing the `margin-inline` property.
3. Run the workflow.
4. Observe that the validator reports an error for the `margin-inline` property.

### What is the current *bug* behavior
The validator does not recognize the `margin-inline` property and returns an error:
```
"file:/github/workspace/./assets/css/style.css": error: CSS: "margin-inline": Property "margin-inline" doesn't exist.
```

**Expected behavior**
The `margin-inline` property should be recognized as valid CSS, as it is part of modern CSS specifications, and the validation should pass without errors.

**Screenshots**
![image](https://github.com/user-attachments/assets/7d37a96b-df17-410b-8042-bfe1d5ca173f)

**Additional context**
The GitHub Action YAML configuration used:
```yaml
name: HTML CSS valid

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tests Integration with Github Actions.
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          root: ./
          css: true
```
The W3C Validator supports this property without issue, and `margin-inline` is part of the modern CSS Logical Properties.

**Comment by Cyb3r-Jak3** [comment]
At first glance, this seems like something related to the upstream library not being up-to-date. Could you try my experimental action using:

```yaml
name: HTML CSS valid

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tests Integration with Github Actions.
        uses: Cyb3r-Jak3/html5validator-action-experimental@master
        with:
          root: ./
          css: true
```

This one uses my fork of html5validator which has a more update to jar file
